/**
 * Where the single publisher account comes from, and whether the admin is
 * allowed to exist at all.
 *
 * Read this alongside lib/keystatic-storage.ts. Two independent gates protect
 * the CMS and both fail closed:
 *
 *   1. This file - is there a configured account to log in as?
 *   2. keystatic-storage.ts - is there a writable storage backend?
 *
 * If either answer is no outside `next dev`, /keystatic does not exist.
 */

export const ADMIN_USERNAME = process.env.ADMIN_USERNAME;
export const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH;
export const AUTH_SECRET = process.env.AUTH_SECRET;

/**
 * A short secret makes the session HMAC forgeable, so it is treated as absent
 * rather than accepted. 32 characters is the floor.
 */
export const authConfigured = Boolean(
  ADMIN_USERNAME &&
    ADMIN_PASSWORD_HASH?.startsWith('pbkdf2.') &&
    AUTH_SECRET &&
    AUTH_SECRET.length >= 32,
);

/** Explains a disabled admin in the server log, so it is not a mystery 404. */
export function authDisabledReason(): string | null {
  if (authConfigured) return null;
  const missing: string[] = [];
  if (!ADMIN_USERNAME) missing.push('ADMIN_USERNAME');
  if (!ADMIN_PASSWORD_HASH) missing.push('ADMIN_PASSWORD_HASH');
  else if (!ADMIN_PASSWORD_HASH.startsWith('pbkdf2.')) {
    missing.push('ADMIN_PASSWORD_HASH (must be generated by `npm run auth:hash`)');
  }
  if (!AUTH_SECRET) missing.push('AUTH_SECRET');
  else if (AUTH_SECRET.length < 32) missing.push('AUTH_SECRET (must be at least 32 characters)');
  return `Missing or invalid: ${missing.join(', ')}.`;
}
